# Generated by Django 4.1.5 on 2023-01-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_game_rounds_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.JSONField(default='{"player1": 0, "player2": 0}'),
        ),
    ]
