# Generated by Django 4.1.5 on 2023-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_image_remove_game_last_move_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draws',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='favorite_move',
            field=models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Paper', 'Paper'), ('Scissors', 'Scissors')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='losses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='most_faced_move',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='most_lost_move',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='most_played_move',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='most_won_move',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='base.room'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
