# Generated by Django 4.1.5 on 2023-01-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0003_alter_game_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.JSONField(default=dict),
        ),
    ]
