# Generated by Django 4.1.5 on 2023-01-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_player_draws_alter_player_favorite_move_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent_moves',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='player_moves',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='result',
            name='opponent_moves',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='result',
            name='player_moves',
            field=models.JSONField(default=dict),
        ),
    ]
