# Generated by Django 4.1.5 on 2023-01-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_game_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='faced_moves',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='played_moves',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='most_faced_move',
            field=models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Paper', 'Paper'), ('Scissors', 'Scissors')], default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='most_played_move',
            field=models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Paper', 'Paper'), ('Scissors', 'Scissors')], default='', max_length=64, null=True),
        ),
    ]
