# Generated by Django 4.1.5 on 2023-01-20 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0006_player_loss_streak_player_win_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='draws',
        ),
    ]
