# Generated by Django 4.1.5 on 2023-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_player_draws'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
