# Generated by Django 4.1.5 on 2023-01-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_round_round_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
